name: prism

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - scipy
  - xarray
  - matplotlib
  - cartopy
  - bottleneck
  - dask
  - netcdf4
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pip

  - pip:
      - regionmask
