#!/bin/bash -l
### Job Name
#PBS -N compute_OHC_casper
### Charging account
#PBS -A UCUC0007
### Request one chunk of resources with 1 CPU and 4 GB of memory
#PBS -l select=1:ncpus=4:mem=60GB:ngpus=0
### Allow job to run up to 1 hour
#PBS -l walltime=6:00:00
### Route the job to the casper queue
#PBS -q casper
### Join output and error streams into single file
#PBS -j oe

mamba activate /glade/work/jonahshaw/conda-envs/hackathon_extended
python /glade/u/home/jonahshaw/Scripts/git_repos/PRISM/J09_OHC_calculation.py

# Write message to PBS log file (stdout)
echo "complete!"
exit 0

### Run with: qsub compute_ohc_casper.pbs